"""add resume link to applications table

Revision ID: 303b836b9ac1
Revises: 1e3e4ed4e650
Create Date: 2023-11-02 17:14:46.790366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '303b836b9ac1'
down_revision: Union[str, None] = '1e3e4ed4e650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('resume_link', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'resume_link')
    # ### end Alembic commands ###
