"""add bookmarked to applications table

Revision ID: 41b520710a06
Revises: 303b836b9ac1
Create Date: 2023-11-03 09:56:05.879204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41b520710a06'
down_revision: Union[str, None] = '303b836b9ac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('bookmarked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'bookmarked')
    # ### end Alembic commands ###
